name: Open Issue

on:
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create or update issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: '⚠️ Open Issue: ${{ github.event.client_payload.subject }}'
          body: ${{ github.event.client_payload.body }}
