name: Unleash Flag Cleanup

on:
  issues:
    types: [opened, labeled]

jobs:
  flag_cleanup:
    if: |
      github.event.label.name == 'unleash-flag-completed'
    runs-on: ubuntu-latest
    steps:
      - name: Unleash Flag Cleanup
        run: |
          echo "Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Cleaning up flag..."
